# Generated by Django 2.2 on 2019-12-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191224_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grade 10'), (2, 'Grade 11'), (3, 'Grade 12')], null=True)),
                ('class_name', models.PositiveIntegerField(blank=True, null=True)),
                ('head_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_teacher', to='users.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='origen_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.OrigenClass'),
        ),
    ]
