# Generated by Django 2.2 on 2019-12-25 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191225_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grade 10'), (2, 'Grade 11'), (3, 'Grade 12')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='origenclass',
            name='grade',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Grade', to='users.Grade'),
            preserve_default=False,
        ),
    ]
