# Generated by Django 2.2 on 2019-12-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20191226_1135'),
        ('users', '0009_auto_20191225_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.Subject'),
        ),
    ]
